extract_job_requirements_task:
  description: >
    Extract key requirements and responsibilities from the job posting.
    Focus on identifying the skills, experiences, and qualifications needed for
    the job.

    Original Job Posting: {job_posting}
  expected_output: >
    A summary of the job requirements including key skills, experiences, and qualifications.

tailor_resume_task:
  description: >
    Adjust the resume content to highlight the most relevant skills and
    experiences for the job posting.
    Frame the content to better fit the job requirements without misrepresenting
    the candidate's abilities.

    Original Job Posting: {job_posting}
    Initial Resume: {linkedin_target_cv_filename}
  expected_output: >
    A tailor-made resume in markdown format that highlights the most relevant
    skills, experiences, and qualifications for the job posting, making sure
    never fake this infromations, it should only include things you know the person
    is good at and can do.
    we are optmizeing for the person to get an interview. do not include ```.
    the resume language should be the same as the language of the job posting.
    save the resume in {crew_generated_resume}.

pdf_to_md_cv_task:
  description: >
    Extract relevant information from the given CV. 
    Focus on skills, experience, education, key achievements, etc.
    Use the PDF tool to extract information from the CV.
    Ensure to capture the candidate's professional summary, technical skills,
    work history, and educational background.

    CV source PDF file: {linkedin_source_cv_filename}
    CV target filename: {linkedin_target_cv_filename}
  expected_output: >
    A structured summary of the CV in MD format
    If you don't find a information, dont mention it on the generated resume.
    Use the create_markdown_file to save the resume in a MD file.
    A resume should look like the following example:
    [YAML]
    # Ciclano da Silva

    ## Professional Summary
    Experienced Software Engineer with a strong background in Python, JavaScript, and RESTful APIs. Proven ability to develop and maintain software applications, collaborate with cross-functional teams, and ensure code quality.

    ## Technical Skills
    - **Programming Languages**: Python, JavaScript
    - **Web Development**: RESTful APIs, HTML, CSS
    - **Frameworks/Libraries**: Django, Flask, React
    - **Tools**: Git, Docker, Jenkins
    - **Databases**: MySQL, PostgreSQL

    ## Work History

    ### Senior Software Engineer
    **Tech Innovations Inc., San Francisco, CA**
    *January 2020 - Present*
    - Developed and maintained multiple web applications using Python and JavaScript.
    - Collaborated with cross-functional teams to design and implement RESTful APIs.
    - Ensured code quality through rigorous testing and code reviews.
    - Automated deployment processes using Docker and Jenkins.

    ### Software Engineer
    **Innovative Solutions LLC, San Francisco, CA**
    *June 2017 - December 2019*
    - Worked on full-stack web development projects using Python and JavaScript.
    - Built and maintained RESTful APIs for various applications.
    - Participated in Agile development processes, including sprint planning and daily stand-ups.
    - Mentored junior developers and conducted code reviews.

    ## Education
    **Bachelor of Science in Computer Science**
    *University of California, Berkeley*
    *Graduated: May 2017*

    ## Key Achievements
    - Successfully led a project to migrate a legacy system to a modern web-based platform, resulting in a 30% increase in performance.
    - Recognized as Employee of the Month for outstanding performance and dedication.
    - Implemented a CI/CD pipeline that reduced deployment times by 50%.

    ## Projects
    - **AI Chatbot**: Developed an AI chatbot using Python and TensorFlow that provides customer support for e-commerce platforms.
    - **Predictive Analytics Platform**: Built a platform that uses machine learning to predict stock market trends, leveraging AWS for deployment and scalability.

    ## Certifications
    - **AWS Certified Solutions Architect** | 2018
    - **Certified Kubernetes Administrator (CKA)** | 2020

    ## Personal Interests
    - AI Research
    - Open Source Contribution
    - Blogging about AI and Machine Learning advancements

    ## Contact Information
    - **Email**: ciclano_da_silva@example.com
    - **Phone**: (123) 456-7890
    - **LinkedIn**: linkedin.com/in/ciclano-da-silva
    - **GitHub**: github.com/ciclano-da-silva
    [/YAML]

